### ISSUE TITLE
Refactor to use structure from the styleguide

### ISSUE THREAD

**Issue by marklagendijk** [ngrx/example-app#100]
Also see #52.

I think @dancancro made some good proposals in the mentioned issue. His [great-big-angular2-example](https://github.com/dancancro/great-big-angular2-example) is a good demonstration of this principle.
The essence of what he is proposing / doing = [official styleguide](https://angular.io/docs/ts/latest/guide/style-guide.html) + ngrx stuff.

I would really prefer that all projects would start using the official styleguide. I think the ideas behind the official styleguide are very good. I also think that the official structure is more familiar for people.

**Comment by brandonroberts** [comment]
This is not a starter project on how to use the style guide. You're welcome to use style guide as a reference

**Comment by dancancro** [comment]
@brandonroberts So.... why not? What do you find problematic about the style guide opinions? If there are pitfalls, I'd like to avoid them.

**Comment by brandonroberts** [comment]
I don't find the style guide opinions problematic, but this example app is not an extension of that guide. I'd rather you focus on how to use the ngrx libraries as opposed to making sure they follow the style guide to the T.

**Comment by dancancro** [comment]
Of course the two things - standards compliance and ngrx focus - are not mutually exclusive.

Hmm, how can I sell this so that it benefits you personally ...

If the project complies with a standard, you can publish that fact prominently at the top of the README: 

**"THIS PROJECT FOLLOWS THE OFFICIAL ANGULAR STYLE GUIDE"**

and maybe even get a link to it added to https://angular.io/

This will increase adoption...

... which will increase contribution... and testing... and project quality...

And other people will do work on the project that you would have otherwise had to do yourself.

And you can spend more time with your friends, dog, cat, girlfriend, kids, or whomever you wish.

And the best part of all: I already did [the work](https://github.com/dancancro/great-big-angular2-example)!

How's that sound? Any better?

**Comment by marklagendijk** [comment]
@brandonroberts would you be open to a pull request which would implement this refactoring?

**Comment by MikeRyan52** [comment]
@dancancro @marklagendijk The example-app is meant to be a learning resource for those new to ngrx. The folder structure is not what @brandonroberts or I would put in production. Instead we are trying to make it as easy as possible for new developers to find files based on how they fit into the ngrx ecosystem (hence top-level folders like reducers, actions, etc).

Is there room for a production-quality example application? Probably. Is that what ngrx/example-app is? Nope.

**Comment by marklagendijk** [comment]
@MikeRyan52 
If that is not what ngrx/example-app is, it should be made clear in the README. You admit that currently it is not of production-quality, but I always assumed it was meant to be.
The risk exists that people will follow 'bad practices' from the example.

One could argue about what the best way to introduce the ngrx ecosystem is. Personally I feel that a familiar structure of production quality would be more helpful. 

@brandonroberts, @MikeRyan52
If you guys are not open to a pull request with this refactoring, would you be open to add it as a separate example repository?

**Comment by dancancro** [comment]
As someone who has gone through dozens and dozens of simplified tutorials in apps structured wrongly and "simply" with the best of intentions, I can attest that it has not made my life easier. It has made it **much** harder. Every time. I don't know where began the position that "simplification" and corner-cutting at the expense of incompatibility and relearning are essential to creating instructional material, but it is as puzzling as it is universal.

Finding a file in a production-style-structured app is not the crippling difficulty that instructors may think. If it takes a minute longer to find a file, the return on this investment will be days or weeks of time saved not scratching one's head at the inconsistencies with the standard. When the app claims no adherence to the standard, there's no way to tell which deviations are accidents, simplifications or innovations. The thing is that it won't take a minute longer to find a file. Just add `tree` output to the README and every file location is clear as crystal.

Consistency is what makes life easy. Inconsistency makes life very hard. A person who has learned the Style Guide way doesn't have to learn the example-app way if it is the same way. And vice versa. Surely that much makes sense.

**Comment by MikeRyan52** [comment]
We are not going to re-align the folder structure to adhere to the style guide. We will continue to optimize the example app to make locating ngrx-relevant code as easy as possible. Any other style guide changes we will consider accepting through pull request. The community is also welcome to fork this repository and provide their own learning experience for developers.

We appreciate the passion around this issue!
