### ISSUE TITLE
Specifying constants in separate folder

### ISSUE THREAD

**Issue by CharlieGreenman** [ngrx/example-app#102]
Hey I've seen this used elsewhere. I know there is currently a discussion revolving [folder structure](https://github.com/ngrx/example-app/issues/52). However, I was wondering why we aren't creating a folder for constants.
Benefits: 
1. All constants in one specific place
2. Interface of sorts to see what is being used in particular section of app.

**Comment by brandonroberts** [comment]
That's reasonable to do, but not within the scope of this example app.
