### ISSUE TITLE
Incompatible types

### ISSUE THREAD

**Issue by kirjai** [ngrx/example-app#114]
I am trying to use this as an example for my own app, however i am getting a Typescript error [on the following assignment from this example app](https://github.com/ngrx/example-app/blob/master/src/app/containers/find-book-page.ts#L28).

`createSelector` (from `reselect` library) function's return type is `Selector<State, boolean>` wrapped in an Observable, where `boolean` is obviously the type of a property i'm trying to get to. So Typescript, understandably, is having a hard time casting `Selector<State, boolean>` to just `boolean`.

```
// index.ts
...
// selector functions
export const getLoginState = (state: State) => state.login;

export const getLoginLoading = (state: State) => createSelector(getLoginState, fromLogin.getLoading);
...
```
```
// where fromLogin is exported from
...
export const getLoading = (state: State) => state.loading;
...
```

```
// component
...
export class MyComponent {
  loading: Observable<boolean>;

  constructor(private store: Store) {
    // here is where the error is
    this.loading = store.selector(fromRoot.getLoginLoading);
  }
}
```
What am i missing here?..

**Comment by brandonroberts** [comment]
`getLoginLoading` shouldn't be a function that returns a selector. It should just return the created selector

```
export const getLoginLoading = createSelector(getLoginState, fromLogin.getLoading);
```

**Comment by kirjai** [comment]
Totally missed that, my bad! Sorry about that and thanks for such a quick response :)
