### ISSUE TITLE
Component: Book Author

### ISSUE THREAD

**Issue by vivekimsit** [ngrx/example-app#120]
I think it would be better to separate `book-author` from `book-authors`.

wdyt?

**Comment by krjordan** [comment]
I'm not sure I follow what you are saying. Can you elaborate?

**Comment by vivekimsit** [comment]
Here:

   ```
    <h5 md-subheader>Written By:</h5>
    <span>
      {{ authors | bcAddCommas }}
    </span>

  ```

Can we have something like:

   ```
    <h5 md-subheader>Written By:</h5>
    <bc-book-author> </bc-book-author>    
```

**Comment by krjordan** [comment]
I don't think creating a `book-author` component is necessary. This adds unnecessary complexity to the `BookAuthorsComponent`.
