### ISSUE TITLE
correct way to write selectors

### ISSUE THREAD

**Issue by dannymarsland** [ngrx/example-app#121]
Having read https://gist.github.com/btroncone/a6e4347326749f938510 which is a fairly thorough introduction to ngrx I saw that selectors were implemented using `store.let()` , however in this project selectors are implemented using `store.select(selectorFunction)`. Could you explain which is the recommended approach and why? Using `store.let()` appears to give you more control over the observable stream to allow caching / preventing unnecessary changes firing. If you use `store.select(selectorFunction)` will this not result in changes firing across your entire store when only a small slice of state has changed?

**Comment by MikeRyan52** [comment]
The corresponding pull request has information about why the change was made: https://github.com/ngrx/example-app/pull/75
