### ISSUE TITLE
HELP: ngrx store freeze

### ISSUE THREAD

**Issue by changalberto** [ngrx/example-app#124]
Does anyone know how to circumvent the error thrown by mutated payload in this example:

![image](https://cloud.githubusercontent.com/assets/24946/23413855/0d514c3a-fda8-11e6-848e-a2665f33b78c.png)

```javascript
  @Effect()
  login$: Observable<Action> = this.actions$
    .ofType(AuthActions.ActionTypes.LOGIN)
    .map((action) => action.payload)
    .switchMap(credential => {
      if(!!!credential) {
        return empty();
      }

      return fromPromise(<Promise<any>>this.auth.login(credential))
        .map((response) => new AuthActions.LoginCompleteAction(response))
        .catch((err) => of(new AuthActions.LoginFailedAction(err)));
    });
```

I keep receiving this error when I pass in the ``response`` as argument rather than the ``action``
![image](https://cloud.githubusercontent.com/assets/24946/23414238/322e2446-fda9-11e6-95c4-c5baf1d01d6b.png)

This is an error coming from [ngrx-store-freeze](https://github.com/codewareio/ngrx-store-freeze). For some reason state is being mutated somewhere unbeknownst to me.

**Comment by krjordan** [comment]
This isn't an issue with the example-app. I would suggest opening an issue on the [ngrx-store-freeze repo](https://github.com/codewareio/ngrx-store-freeze/issues).
