### ISSUE TITLE
The Discriminating Unions pattern not working on the latest Typescript version (2.2.1)

### ISSUE THREAD

**Issue by chigur** [ngrx/example-app#127]
Hello,

This example application uses a pattern called [Discriminating Unions](https://www.typescriptlang.org/docs/handbook/advanced-types.html) to provide following features:

* Ensure that the action types are unique.
* Ensure that the action payload type is inferred properly in the reducers.

The issue I am facing is this: the type of the action payload is not correctly inferred if the latest Typescript compiler is used (2.2.1 in this case). But, if the version of the compiler used is 2.0.10, then everything works fine. Following is the console dump:

    ajinkya@idea-PC /f/work/beats/src/app (product-listing +$=)
    $ tsc --version
    Version 2.2.1

    ajinkya@idea-PC /f/work/beats/src/app (product-listing +$=)
    $ tsc && echo "exited without error"
    reducers/products.ts(27,34): error TS2339: Property 'map' does not exist on type 'Product[] | "hotels" | "activities"'.
    Property 'map' does not exist on type '"hotels"'.

    ajinkya@idea-PC /f/work/beats/src/app (product-listing +$=)
    $ ../../node_modules/.bin/tsc -version
    Version 2.0.10

    ajinkya@idea-PC /f/work/beats/src/app (product-listing +$=)
    $ ../../node_modules/.bin/tsc && echo "exited without error"
    exited without error

    ajinkya@idea-PC /f/work/beats/src/app (product-listing +$=)
    $

**Comment by varghesep** [comment]
I also see the same problem.

In the [book reducer](https://github.com/ngrx/example-app/blob/master/src/app/reducers/books.ts), on line 24, there is a filter method on the payload which can be of type string, Book[], Book etc.... This is because Actions is a type alias on the line [56 of the Book actions](https://github.com/ngrx/example-app/blob/master/src/app/actions/book.ts).

**Comment by lucastheisen** [comment]
This feels rather _icky_ but this is what I did in my project:

```
import { Action } from '@ngrx/store';
import { type } from '../util';

export interface ActivateAction extends Action {
    type: '[Viewer] Activate';
}

export interface RegisterAction extends Action {
    type: '[Viewer] Register';
}

export const ActionTypes = {
    ACTIVATE: type((<ActivateAction>{type:'[Viewer] Activate'}).type),
    REGISTER: type((<RegisterAction>{type:'[Viewer] Register'}).type)
}

export type Actions = 
    ActivateAction | 
    RegisterAction;
```

Its certainly not very dry, but it does preserve the type safety, and the ugliness remains hidden from the user...

**Comment by krjordan** [comment]
The example app is currently using `2.0.X`. We plan on upgrading typescript once Angular 4 is released. See @MikeRyan52's [comment](https://github.com/ngrx/example-app/pull/88#issuecomment-272623083) for more info.
