### ISSUE TITLE
Error building example app on Windows 10 64 bit

### ISSUE THREAD

**Issue by abidmix** [ngrx/example-app#13]
Build process fails on Windows . I have attached screenshots and the npm debug log

[npm-debug.txt](https://github.com/ngrx/example-app/files/301731/npm-debug.txt)
![error](https://cloud.githubusercontent.com/assets/12702893/15844329/5f8c6504-2c37-11e6-8bcc-b306abb2c89f.JPG)

**Comment by tja4472** [comment]
Port 8080 is already in use.

netstat -nao | find "8080"

http://www.howtogeek.com/howto/28609/how-can-i-tell-what-is-listening-on-a-tcpip-port-in-windows/

**Comment by abidmix** [comment]
@tja4472 . Port 8080 was indeed and is use by a system process and could not release it. I ended up specifying another port in the webpack.config.js like so                                                   `devServer: {
    inline:true,
    port: 8008
  },`                                                                                                                                                                      Thank you for pointing me in the right direction
