### ISSUE TITLE
Time Travel "Jump" doesn't work in 3.2.2

### ISSUE THREAD

**Issue by pclements12** [ngrx/example-app#130]
I visited the live version of the example app here:
http://ngrx.github.io/example-app

Using the Redux Dev Tools extension in Chrome
I can skip Actions that have occurred as expected, but the "Jump" functionality does not seem to work at all.

I'm using Redux Dev Tools extension version 2.14.2 (the latest as of today)
Chrome Version 56.0.2924.87 (64-bit) on Mac

**Comment by krjordan** [comment]
This doesn't seem to be an issue with the example-app specifically. I would suggest opening this issue in the [@ngrx/store-devtools](https://github.com/ngrx/store-devtools/issues) repo.
