### ISSUE TITLE
Update with angular-cli 1.0.0

### ISSUE THREAD

**Issue by Waterstraal** [ngrx/example-app#134]
angular-cli 1.0.0 has been released, it would be nice to update this project using that version

**Comment by Waterstraal** [comment]
Which of course has updated angular dependencies to 4.0.0

**Comment by Kaffiend** [comment]
Would like this as well.

**Comment by axtho** [comment]
Will that use the new ngrx/platform or will the other repos be updated to all the latest deps?

**Comment by changalberto** [comment]
Please also make sure that TS goes through proper linting, and that we are also using`ngrx-store-freeze` properly in the effects where payloads are frozen in dev https://github.com/codewareio/ngrx-store-freeze/issues/5.

Thanks!
