### ISSUE TITLE
SCSS support

### ISSUE THREAD

**Issue by snellcode** [ngrx/example-app#136]
If anyone has some idea how to support SCSS, I would greatly appreciate some tips?

**Comment by krjordan** [comment]
If you're generating a new project with the Angular CLI you can use the `--style scss` flag. To change the example-app to use `scss` instead of `css`, the following should do it:

* Rename the `src/styles.css` to `src/styles.scss`.
* Change the styles array inside the `.angular-cli.json` file to:
```
"styles": [ 
  "styles.scss"
],
```
