### ISSUE TITLE
Production build missing html file

### ISSUE THREAD

**Issue by snellcode** [ngrx/example-app#137]
Prod build gives me only the js files. Is it also supposed to output an html file with the correct links to the built js files?

**Comment by krjordan** [comment]
Yes, there should be an index.html file with the js files linked. You can take a look at our gh-pages branch for the files.

**Comment by snellcode** [comment]
ok. does this mean that something is missing from master branch to include that functionality into the build command? I'm not sure if this is something I'm doing wrong, or if there is missing functionality? thanks again for the help!

**Comment by krjordan** [comment]
Everything seems to be working correctly on master. I'm able to run `npm run build` along with `ng build` to build the js files, including the `index.html` file. If you give me some details about your development environment, I can try to help you debug further.
