### ISSUE TITLE
Decouple container component and selectors

### ISSUE THREAD

**Issue by varghesep** [ngrx/example-app#142]
I think the container components and the selectors are coupled. The following code in [this ](https://github.com/ngrx/example-app/blob/0bd88242cadf243bdbec581417a833b5add6d14a/src/app/containers/find-book-page.ts) is an example. 

```
constructor(private store: Store<fromRoot.State>) {
    this.searchQuery$ = store.select(fromRoot.getSearchQuery).take(1);
    this.books$ = store.select(fromRoot.getSearchResults);
    this.loading$ = store.select(fromRoot.getSearchLoading);
  }
```

I would like to suggest to inject these selectors which can make also these containers testable.

The [index reducer](https://github.com/ngrx/example-app/blob/0bd88242cadf243bdbec581417a833b5add6d14a/src/app/reducers/index.ts) may become unmaintainable after a point. If OOPs design pattern is used, the related selectors can be put behind a class that takes the store state in the constructor.

**Comment by brandonroberts** [comment]
The containers can be tested easily by providing a certain state and asserting that the component behaves as intended. The selectors aren't coupled to the component as they can be used anywhere. Its better to use them in container components and have other components only be responsible for displaying data and providing data from interaction. Organizing your selectors by feature areas would help to alleviate the growing index reducer, but its the place you want to expose as the "public api"

**Comment by cgatian** [comment]
I think the OP is suggesting the container is coupled to the store, which it is.
