### ISSUE TITLE
Reasoning for selector duplications and usage.

### ISSUE THREAD

**Issue by mxchange** [ngrx/example-app#145]
I see a lot of duplication in the reducers like `getEntities` and then `getBookEntities` in the index reducer. 
I'm curious what the main reasoning behind this is.

Also selectors like `getSelected` and `getAll` are only used in tests at the moment. Is there a plan to implement this in the future somewhere.

**Comment by krjordan** [comment]
To be able to use the `getEntities` selector, it needs to be wrapped with a new selector `getBookEntities`. Check out the [comments](https://github.com/ngrx/example-app/blob/master/src/app/reducers/index.ts#L104) inside the code.

>Every reducer module exports selector functions, however child reducers have no knowledge of the overall state tree. To make them useable, we need to make new selectors that wrap them.

>The createSelector function from the reselect library creates very efficient selectors that are memoized and only recompute when arguments change. The created selectors can also be composed together to select different pieces of state.

`getSelected` is being used in the [selected-book-page.ts](https://github.com/ngrx/example-app/blob/master/src/app/containers/selected-book-page.ts#L27) file and the `getAll` selector was most likely used early on before it was refactored. So as far as using it in the future, I can't say at the moment, but it can probably be removed.
