### ISSUE TITLE
reselect type errors with v3.0.0

### ISSUE THREAD

**Issue by goelinsights** [ngrx/example-app#148]
Anyone else getting type errors breaking the build in bumping to reselect to 3.0.0 from 2.5.4? Using the angular CLI/ webpack 

ERROR in ...node_modules/reselect/lib/index.d.ts (11,63): An interface may only extend a class or another interface
webpack: Failed to compile.

**Comment by brandonroberts** [comment]
Its a known issue with a PR in to fix it: https://github.com/reactjs/reselect/pull/240
