### ISSUE TITLE
Update to ngrx 4

### ISSUE THREAD

**Issue by avatsaev** [ngrx/example-app#169]

**Comment by linkvt** [comment]
The example app of ngrx 4 is also placed in the new ngrx/platform mono repo, see here: https://github.com/ngrx/platform/tree/master/example-app

This repo should probably be marked out of date as the [others](https://github.com/ngrx/store).

**Comment by avatsaev** [comment]
Thank you, didn't notice that.

Yes I agree, this repo needs to be marked as out of date and redirect to the mono repo
