### ISSUE TITLE
Pages are smart?

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/example-app#17]
In this example the pages are the smart.
if I want to use same logic code which in the page, for a different page, should I copy it? it's not about consume the smart with there logic inside and place the smart on several pages?

**Comment by akomm** [comment]
what logic would it be? so far in my situation it was always something that was a dumb component at the end or service/effect, etc.

**Comment by MikeRyan52** [comment]
We renamed `pages` to `containers` to prevent confusion. Container components are smart but being smart doesn't prevent you from re-using them.
