### ISSUE TITLE
switchMap/exhaustMap in effects - best practice.

### ISSUE THREAD

**Issue by icbmike** [ngrx/example-app#171]
When doing an effect of the sort (execute fetch -> fetch arrived | fetch failed) I see a lot of examples that do the result action mapping inside switchMap or exhaustMap:

    @Effect()
    search$: Observable<Action> = this.actions$
      .ofType(book.SEARCH)
      .map(toPayload)
      .switchMap(query => 
          this.googleBooks.searchBooks(query)
            .map(books => new book.SearchCompleteAction(books))
            .catch(() => of(new book.SearchFailedAction()));
      );

My friend and I were arguing about whether the snippet below is equivalent:

    @Effect()
    search$: Observable<Action> = this.actions$
      .ofType(book.SEARCH)
      .map(toPayload)
      .switchMap(query => this.googleBooks.searchBooks(query))
      .map(books => new book.SearchCompleteAction(books))
      .catch(() => of(new book.SearchFailedAction()));

I think that it is equivalent and is better because the switchMap covers the behaviour that is most relevant to the timing and you've also reduced the amount of nesting, but the majority of examples don't do this.

Is it because they aren't equivalent or is it a best practice?

**Comment by Vaelyr** [comment]
I believe that the 2nd snippet is not doing error handling correctly. You need to catch the error inside the switchMap.

**Comment by brandonroberts** [comment]
@Vaelyr is correct
