### ISSUE TITLE
Why not make the state immutable by using 'readonly'?

### ISSUE THREAD

**Issue by matze1234** [ngrx/example-app#172]
Hello,
i have a question, i hope this is the right place:
I saw that since typescript 2.0 you can create immutable objects by declaring them as 'readonly'.
So my question is, why don't you make use of that, since the state is supposed to be immutable.

**Comment by krjordan** [comment]
It is currently being used in [ngrx version 4](https://github.com/ngrx/platform/tree/master/example-app).
