### ISSUE TITLE
StoreModule.provideStore is now deprecated

### ISSUE THREAD

**Issue by SergioArrighi** [ngrx/example-app#173]
Hello,

I know that StoreModule.provideStore is now deprecated and we are supposed to use forRoot.
I'm a beginner with ngrx and typescript and I don't get hot to replace that instruction with forRoot in my pet project inspired to this app.
Thanks for help.
Best regards

**Comment by LimarenkoDenis** [comment]
@SergioArrighi, This app uses "@ngrx/store": "^2.2.2", and that's why it still `StoreModule.provideStore` syntax. If you want the latest version with `forRoot`, take a look at https://github.com/ngrx/platform/tree/master/example-app

**Comment by SergioArrighi** [comment]
Thanks a lot @LimarenkoDenis for the quick reply, this one makes so much more sense to my inexperienced eye eheheheh.
Best regards and thanks for the awesome job!

**Comment by ildafon** [comment]
как вы заебали со своими is now deprecated
