### ISSUE TITLE
Provide an update example

### ISSUE THREAD

**Issue by dimmank** [ngrx/example-app#174]
Hi! There is an add and delete example in the app, but not an update example.
I've seen a lot of suggestions but a recommended one in this app would really nice!
Hm, the books/collection example may be a little strange to have an update scenario now thinking about it. You'll figure it out! :)
Thanks!

**Comment by krjordan** [comment]
This version of the example-app won't be getting any new features. However, feel free to add a feature request on the [updated example-app](https://github.com/ngrx/platform).

**Comment by dimmank** [comment]
Okay, thanks! 👌
