### ISSUE TITLE
Observer not working when store obj update

### ISSUE THREAD

**Issue by mithabavkar** [ngrx/example-app#175]
I did same thing in my application. On click of menu icon store data is update but that time observer not called.
My component structure is,
global Component
          |
Header Component      Sidebar Component      Home Component      Footer component

Global Component is parent component and these four of child component but these four component are sibling component each other.

Menu icon is placed inside header component and click event emit into global component and fire dispatch event from global component. After that nothing happen. 

Kindly help me to get it out of it.

Thanks in advance..!!

**Comment by krjordan** [comment]
I would recommend reaching out on [Gitter](https://gitter.im/ngrx/platform) for support and questions.
