### ISSUE TITLE
More object orientedness for actions?

### ISSUE THREAD

**Issue by mwawrusch** [ngrx/example-app#18]
From previous experience in larger enterprise client server apps many years ago it seemed that encapsulating actions in individual classes is a better way to go for larger apps than exposing functions. Might be worth considering, even if it's a bit more typing.

Untested sample:

```
import { Injectable } from '@angular/core';
import { Action } from '@ngrx/store';

@Injectable()
export class VenueGetOneAction implements Action {
  static ACTION = '[Venue] GetOne';

  type: string = VenueGetOneAction.ACTION;
  payload: any;

  constructor(venueId: string) {
    this.payload = {
      id: venueId
    };
  }
}

```

**Comment by chapati23** [comment]
@mwawrusch, i don't understand. what would be the advantage over plain old functions? can you elaborate?

**Comment by MikeRyan52** [comment]
Definitely doing this with the next upgrade

**Comment by MikeRyan52** [comment]
This is now in master as a means to take advantage of tagged union types. Makes reducers much more strongly typed.
