### ISSUE TITLE
Peerdependecy error running npm install for example-app

### ISSUE THREAD

**Issue by kpgarrod** [ngrx/example-app#20]
I have cloned the example-app and run `npm install` and I get these messages:

```
 optional dep failed, continuing fsevents@1.0.12
npm WARN cannot run in wd angular2-webpack-lite@1.0.0 npm run typings -- install (wd=/home/Documents/example-app)
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/forms@0.2.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular2-material/input@2.0.0-alpha.6 wants @angular/forms@^0.1.0

npm ERR! Please include the following file with any support request:
npm ERR!     /home/Documents/example-app/npm-debug.log
```

I guess it's something trivial but not sure what the right solution is so no pull request.

**Comment by greglockwood** [comment]
I got this issue yesterday, too and was unable to resolve it myself.

It took me a while to figure out I could run the app anyway using `npm run start`, so it may be a stumbling point for others, too.

**Comment by kpgarrod** [comment]
The application wouldn't start for me. I realised that I had not set the Node version for the new directory and so was using the system default which on my Ubuntu 16.04 OS was earlier than the required version. Once I did `nvm use 6.0` the app installed and ran correctly.
