### ISSUE TITLE
composing selectors

### ISSUE THREAD

**Issue by akomm** [ngrx/example-app#23]
the select operator returns an plain subject, which does not have the select operator, therefore the example composing selectors does not work. The second function in the composition throws.

```ts
// src/reducers/workflow.ts

export function getEntities() {
  return (state$: Observable<WorkflowState>) => state$
      .select((s: WorkflowState) => s.entities)
}
```

```ts
// src/reducers/index.ts
export function getWorkflowState() {
  return (state$: Observable<AppState>) => state$
    .select((s: AppState) => s.workflow)
}

export function getWorkflowEntities() {
  return compose(fromWorkflow.getEntities(), getWorkflowState());
}
```

```ts
// then
state.let(getWorkflowEntities())
```

causes
`EXCEPTION: TypeError: state$.select is not a function` 
on the second function in chain (getEntities)

This seem obvious to me, because the select-operator is only available in Store:
https://github.com/ngrx/store/blob/19d9fe3f92bd57ffae541039109f6e6fcd686295/src/store.ts#L21

I did not find any source which would inject it into the rxjs Subject. So how should the compose-example work?

**Comment by akomm** [comment]
Okay. I'v found the adder:

https://github.com/ngrx/core/blob/770376346c615ab46d1b62233ffcd039d8ea35d0/lib/add/operator/select.ts

**Comment by lanocturne** [comment]
How did you solve the error? I am encountering this issue at 2.0(final) version.

**Comment by akomm** [comment]
import the file I'v linked where you use the .select
