### ISSUE TITLE
Input (blur) event and @Input() value

### ISSUE THREAD

**Issue by sanex3339** [ngrx/example-app#29]
I have a problem.

At first - use case:
I want to set default value for input on `blur` event, if input value is empty.

Input:
```
            <input 
                id="format" 
                class="form-control" 
                type="text" 
                [value]="inputValue" 
                (keyup)="keyup$.next($event.target.value)"
                (blur)="blur$.next($event.target.value)"
            >
```

`[value]="inputValue"` - `@Input` value of dumb component, taken from `store -> format`.
I take the value from the `store` in this way:
```ts
//main component

//template
template: `<format-input [inputValue]="format$ | async" (outputValue)="updateFormat($event)"></format-input>`

this.format$ = this.store.let(getFormat());

//form-reduser.ts
export function getFormat () {
    return (state$: Observable<GeneratorFormState>) => state$
        .map(s => s.format);
}
```

Both `keyup` and `blur` run action `updateFormat`.

My problem is what after `blur` event `[value]="inputValue" `will not update if value, which was inserted in the `store` was the same as previous `store` value.

For example:
1) store value: 22 => input value: 22 => clearing (cut) input value => blur event => input is empty, setting default value (1) to the store => store value: 1 => input value: 1
2) store value: 1 => input value: 1 => clearing (cut) input value => blur event => input is empty, setting default value (1) to the store => store value: 1 => input value: '' (empty)

So, how i can fix this?

**Comment by sanex3339** [comment]
Seems Angular ngOnChanges not firing when previousValue same as currentValue

**Comment by sanex3339** [comment]
https://plnkr.co/edit/Rvz2ElLjM20R3nC6ZQWt?p=preview

Enter in input 123, then click outside of the input. parent value will be 123. Then delete all input content and click again outside of the input - parent value will be set as DEFAULT_VALUE (1) and input will be updated instantly with default value. Then delete input value (1) again - parent value will be set as DEFAULT_VALUE (1) but input value will not updated with default value and will be empty '' because previous @Input() value was been the same as current @Input() value (1)

**Comment by MikeRyan52** [comment]
@sanex3339 Were you able to solve your issue? If not, feel free to open another one. Sorry for the late response!
