### ISSUE TITLE
'books' in state not being cleared?

### ISSUE THREAD

**Issue by kevindqc** [ngrx/example-app#32]
Hi,

I'm new to ngrx and redux so maybe this is normal, but when I search something, I see book IDs added to the `search` state property, and the book added to the `books` state property. That's fine.

However, it seems like the `books` property state is never emptied, leaking books? So if I search 10 different terms, the `search` will have the latest 10 book ids, my `collection` is empty, however the `books` will have 100 books, 90 of them that shouldn't be there and just waste memory?

**Comment by MikeRyan52** [comment]
Expiring the book cache is left as an exercise for developers. Including it in the example would increase the complexity of the example to the detriment of the learning experience.
