### ISSUE TITLE
switchMap fails on actions$ of type Actions

### ISSUE THREAD

**Issue by leudanielm** [ngrx/example-app#35]
Version: 2.0.0-beta.2

When trying to do a `switchMap` on `this.actions$` which is of type Actions, it fails with this error:
_this.actions$.ofType(...).switchMap is not a function_
Also tried importing it from `rxjs/operator`, doesn't fix it.

**Comment by orizens** [comment]
hi @leudanielm 
i'm on beta.3 (http://github.com/orizens/echoes-ng2).
did you import it this way: ```import 'rxjs/add/operator/switchMap';```

**Comment by leudanielm** [comment]
Hi @orizens, I will close this issue, it works now, it was indeed because I was importing `rxjs/operator/switchMap` instead of `rxjs/add/operator/switchMap`.

Thanks!
