### ISSUE TITLE
[routerLink]="['/book', id]" - click event not triggering Route change

### ISSUE THREAD

**Issue by MarkPieszak** [ngrx/example-app#40]
Tested in Chrome, can't navigate to specific book route now (although manually entering it the Route works completely fine), it might be because the project is using an older Router at the moment. Can look into it further tomorrow and try and get a PR fix for it in.

It also seems to be very sporadic, sometimes the link works, other times it doesn't.

book-preview.ts

    <a [routerLink]="['/book', id]" <--

**Comment by MarkPieszak** [comment]
Magically went away, disregard!

**Comment by MikeRyan52** [comment]
This should be fixed now as of the most recent updates.

**Comment by MarkPieszak** [comment]
Great!
Hey @MikeRyan52 let me know how I can help be a part of all the NgRx awesomeness :)
