### ISSUE TITLE
current rc5 branch: brower history duplication

### ISSUE THREAD

**Issue by monad98** [ngrx/example-app#46]
To go back/forward with browser back/forward button, I have to click twice. No error message.
After update ngrx/core, ngrx/router-store.. , same problem happens.

**Comment by monad98** [comment]
It seems that multiple bootstrap components are causing problems. Moving ````<bc-devtools></bc-devtools>```` from index.html to AppComponent's template and removing DevtoolsComponent from ````@NgModule.bootstrap```` solves this problem.

**Comment by krjordan** [comment]
Looks to be fixed as I'm unable to reproduce after the upgrade to Angular 2 final. Re-open this issue if you're still seeing this and we'll investigate it further.
