### ISSUE TITLE
question: best practice for composition of selector functions

### ISSUE THREAD

**Issue by nitimmerman** [ngrx/example-app#49]
Hi,

First of all: Thank you very much for this helpfull demo application!
I have a question about the composition of the selector functions.
In your demo app you define each selector twice, once in the  book/ search reducer and once in the toplevel redurer to compose the 'actual' reducer function with the app state.
At the moment I work at an app which will ultimately consists of 15+ modules each with 10 to 100 components. I'am afraid that if I follow this approach the code in the toplevel reducer will become very difficult to manage.
Besides that, it feels as a bit of overhead to define each selector function twice. Would it be possible to inject the state top-down or is this impossible/bad practice?

What are your recommendations?

**Comment by metanav** [comment]
You can create index.ts for each modules which contains all top level selectors for that module and import all module/index.ts in the main module index.ts.
