### ISSUE TITLE
What is recommended folder structure?

### ISSUE THREAD

**Issue by Aurimas86** [ngrx/example-app#52]
Right here, I see it's by type. It lets to do barrels easily, but when working on feature, you need to switch between 6 or 8 different folders, and each of them contains a lot of files.

Best practices says it should be by feature, but those examples are way too primitive - contains component, html and css only. When working with ngrx that feature would contain effects, services, reducers, pages/components, etc.. They cannot be barreled into one index.ts file, as it must be spread across declarations/providers/effects in module file.

Any suggestions how to do it correctly?

**Comment by dancancro** [comment]
I'm wondering the same thing. The direction of Google's example app and style guide [says](https://angular.io/docs/ts/latest/guide/style-guide.html#!#app-structure-and-angular-modules) to divide by feature. Perhaps as a consequence of this, it also [says](https://angular.io/docs/ts/latest/guide/style-guide.html#02-01) to put the thing-type - 'component', 'module', etc - in the file name which this approach doesn't do. Short file names are nice but can also be confusing. It's a tradeoff.

I'm working on my first Angular2/Redux app and have chosen to prioritize practices of these great but incongruent expert opinions in the following order loosely based on what I think the market share is. Whenever opinions on the same thing conflict between two different paradigms, I'm using that of the higher one on this list. Let me know how you would order them or if you'd consider other ones.

1. [Angular Style Guide](https://angular.io/docs/ts/latest/guide/style-guide.html) by Google
2. [Tour of Heroes Final Version](https://angular.io/resources/live-examples/ngmodule/ts/plnkr.html) by Google
3. [Angular CLI](https://github.com/angular/angular-cli) by Google and the community
4. [ngrx example app](https://github.com/ngrx/example-app)
5. [ng2-state-talk based on Angular-CLI](https://github.com/JavascriptMick/ng2-state-talk) by [@JavascriptMick](https://github.com/JavascriptMick) 
6. [rangle-starter - Angular 2 with TypeScript and Redux version](https://www.npmjs.com/package/rangle-starter) by [@SethDavenport](https://github.com/SethDavenport)

So far I've tried to take @JavascriptMick's project and bring it into compliance with the Google Style Guide as [this fork](https://github.com/dancancro/ng2-state-talk). Now I'm working on integrating the styles and practices of this ngrx example-app into it.

@Aurimas86 I don't think I understand your last sentences. Are you saying that organizing by feature would present a barrel problem or organizing the way files currently are in the example-app presents a barrel problem? Thanks.

**Comment by Aurimas86** [comment]
@dancancro About barrels: when I group by feature: components, services, effects end up in same directory. At this point I cannot use single index.js barrel in that folder for all those different exports (Or can I?). I need different index.js for each type somewhere else, so I can include these barreled types in module.

**Comment by dancancro** [comment]
As far as I know, an index.js file is just like any other js file and can technically import from files anywhere else but there is an understanding that they are indexes of their folders' contents and so they should only import from other files in their own folders.

But I'm more interested in the usage of barrels at all. What is the compelling reason to write import statements that use barrels instead of import statements that refer to the files that the index files aggregate? And what is the rationale for having these index files aggregate files in one or another manner?

Answering these questions will help me understand the reasons for organizing files one way or another. I'm sure there are good reasons but I'm new and don't know what they are.

**Comment by dancancro** [comment]
What do you think of this file structure?

- For scalability, files are grouped by Feature, not Type
- Store files are separate from UI files
- There is a small set of file names - "component.ts", "module.ts", "routing.ts", etc. All domain-specific words go into folder names only. This makes it DRYer. Instead of `app/admin/admin.module.ts` there's `app/admin/module.ts` The class in `app/admin/module.ts` is named `AdminModule`.
- smart, container components are named `page.ts` instead of `component.ts` to distinguish them from dumb components.

https://gist.github.com/dancancro/ecb53d1bf5b1fa0dde00638a554af7d5

```
.
├── app
│   ├── module.ts
│   ├── page.css
│   ├── page.html
│   ├── page.spec.ts
│   ├── page.ts
│   ├── routing.ts
│   ├── core
│   │   ├── about
│   │   │   └── page.ts
│   │   ├── module.ts
│   │   ├── routing.ts
│   │   └── store
│   │       ├── books
│   │       │   ├── book
│   │       │   │   ├── actions.ts
│   │       │   │   ├── effects.ts
│   │       │   │   └── model.ts
│   │       │   └── reducer.ts
│   │       ├── claims
│   │       │   ├── claim
│   │       │   │   ├── actions.ts
│   │       │   │   ├── model.ts
│   │       │   │   └── reducer.ts
│   │       │   ├── actions.ts
│   │       │   └── reducer.ts
│   │       ├── collection
│   │       │   ├── actions.ts
│   │       │   ├── effects.ts
│   │       │   └── reducer.ts
│   │       ├── counter
│   │       │   ├── actions.test.ts
│   │       │   ├── actions.ts
│   │       │   ├── model.ts
│   │       │   └── reducer.ts
│   │       ├── debate
│   │       │   ├── data.service.ts
│   │       │   └── effects.ts
│   │       ├── index.ts
│   │       ├── layout
│   │       │   ├── actions.ts
│   │       │   └── reducer.ts
│   │       ├── notes
│   │       │   ├── note
│   │       │   │   ├── actions.ts
│   │       │   │   ├── model.ts
│   │       │   │   └── reducer.ts
│   │       │   ├── data.service.ts
│   │       │   ├── actions.ts
│   │       │   ├── effects.ts
│   │       │   └── reducer.ts
│   │       ├── rebuttals
│   │       │   ├── rebuttal
│   │       │   │   ├── actions.ts
│   │       │   │   ├── model.ts
│   │       │   │   └── reducer.ts
│   │       │   ├── actions.ts
│   │       │   └── reducer.ts
│   │       ├── search
│   │       │   └── reducer.ts
│   │       └── session
│   │           ├── actions.ts
│   │           ├── model.ts
│   │           └── reducer.ts
│   ├── counter
│   │   ├── component.ts
│   │   ├── module.ts
│   │   ├── page.ts
│   │   └── routing.ts
│   ├── debate
│   │   ├── claim
│   │   │   ├── component.css
│   │   │   ├── component.html
│   │   │   ├── component.spec.ts
│   │   │   └── component.ts
│   │   ├── module.ts
│   │   ├── page.css
│   │   ├── page.html
│   │   ├── page.ts
│   │   ├── routing.ts
│   │   └── rebuttal
│   │       ├── component.css
│   │       ├── component.html
│   │       ├── component.spec.ts
│   │       └── component.ts
│   ├── login
│   │   ├── login-form
│   │   │   ├── component.test.ts
│   │   │   └── component.ts
│   │   ├── login-modal
│   │   │   ├── component.test.ts
│   │   │   └── component.ts
│   │   └── module.ts
│   ├── notes
│   │   ├── add-button
│   │   │   ├── component.css
│   │   │   ├── component.html
│   │   │   └── component.ts
│   │   ├── note
│   │   │   ├── component.css
│   │   │   ├── component.html
│   │   │   ├── component.ts
│   │   ├── module.ts
│   │   ├── page.css
│   │   ├── page.html
│   │   ├── page.spec.ts
│   │   ├── page.ts
│   │   └── routing.ts
│   └── shared
│       ├── alert
│       │   ├── component.test.ts
│       │   └── component.ts
│       ├── assets
│       │   └── bernie-sanders-128.jpg
│       ├── button
│       │   ├── component.test.ts
│       │   └── component.ts
│       ├── container
│       │   ├── component.test.ts
│       │   └── component.ts
│       ├── draggable
│       │   └── directive.ts
│       ├── form
│       │   ├── component.ts
│       │   └── test.ts
│       ├── form-error
│       │   ├── component.ts
│       │   └── test.ts
│       ├── form-group
│       │   ├── component.ts
│       │   └── test.ts
│       ├── input
│       │   ├── component.ts
│       │   └── test.ts
│       ├── label
│       │   ├── component.ts
│       │   └── test.ts
│       ├── logo
│       │   ├── component.test.ts
│       │   ├── component.ts
│       │   └── component.css
│       ├── modal
│       │   ├── component.test.ts
│       │   ├── component.ts
│       │   └── component.css
│       ├── modal-content
│       │   ├── component.test.ts
│       │   └── component.ts
│       ├── shared.module.ts
│       ├── ui
│       │   └── module.ts
│       └── util.ts
├── config
│   ├── environment.prod.ts
│   └── environment.ts
├── favicon.ico
├── index.html
├── main.ts
├── polyfills.ts
├── styles.css
├── test.ts
├── tsconfig.json
└── typings.d.ts
```

**Comment by metanav** [comment]
In my opinion, all related things should be in same directory as a feature module. This would improve de-coupling and you can add/remove features as required.  Things which are  common should go in share module.

**Comment by CharlieGreenman** [comment]
First off, @dancancro, great idea with separating Store and UI. Really is a novel idea and got me thinking. Regardless, I agree with @metanav regardless of how things have been done in the past and with other classic redux projects. I think everything should be put in the same folder. However, if one were to include e2e.js testing, as well as spec testing, one is potentially looking at 10 files in a single component. I really like the idea of breaking up a single component into three folder. 

Let's imagine the following is a component a part of our component called book. It would be something similar to:


```
├── app
│   ├── book
│   │  ├── store
│   │  │  ├── actions.ts
│   │  │  ├── effects.ts
│   │  │  ├── model.ts
│   │  │  └── reducer.ts
│   │  ├── ui
│   │  │   ├── component.css
│   │  │   ├── component.html
│   │  │   └── component.ts
│   │  ├── tests
│   │  │   ├── component.spec.ts
│   │  │   └── component.e2e..ts
```

So, what do you think? Obviously, there is still more work to be done(how it fits into the complete tree structure above). However, I really like the idea of having everything centralized to specific components like @metanav mentioned and separating folders to make the folder tree structure cleaner, similar to how @dancancro you mentioned, separating each component into three folders for the store, ui and tests.

**Comment by dancancro** [comment]
@CharlieGreenman  It's really important to recognize that there is a book **feature** and a book **store slice** (a.k.a. table, a.k.a. entity type). They happen to have the same name here, "book", and a 1:1 relationship but this is not at all the rule.

Because of this, it really isn't feasible to have just one "book" folder to contain both the entity code and the feature code. There needs to be exactly one for the book entity code and there should be one for each **feature** that deals with books - the publishing feature, the orders feature, the reviews feature, etc..  It's not really a novel idea. I was using the same approach writing MS Access programs in the '90s. - tables were in one place and forms another and the relationship between them was many-to-many.

Into these feature folders should go the user interface component and component testing code. Into `/store/book` should go the code for defining (model.ts), reducing (reducer.ts), and acting upon (actions.ts) book state as well as the tests of this code. I'm undecided about where effects should go. In my app, they are imported in feature modules which are in the feature folders but it seems that they can execute in response to activity from any feature so they should instead be imported in a new `StoreModule`.

If we put the book store code into the book feature folder and have the publishing feature refer to it when it needs books, then that makes the "book" feature a kind of first class feature and the publishing feature second class. To set up a pecking order of features in every instance is unnecessary and just makes life harder.

Make sense?

A couple of thoughts since my last post...

I'm on the fence about shortening `/book/book.model.ts` to `/book/model.ts`. I love shortening things but it could make it confusing to see several files in an IDE with the same name. But maybe not and DRY is a nice practice. I've been doing a lot of copying and pasting while trying this out and shortening the names would reduce that work a little with less to change in the import statements.

I am warming up to the idea of establishing a few different common sorts of component file and component class name - component.ts (SearchComponent), page.ts (AdminPage), list.ts (BookList), detail.ts (OrderDetail), etc. If we all understand that a page is a kind of component and agree on what it means to be a page, then we can name something `AdminPage` instead of `AdminPageComponent` for example, and know that it is decorated with `@Component` and all else that goes with being a component, and a page.

If you would like to see how my thoughts are evolving, [here](https://github.com/dancancro/great-big-angular2-example) is the app I'm making to learn this.

**Comment by vespertilian** [comment]
@Aurimas86 great issue I am having the same thoughts. 
@dancancro I like the way you are heading, by feature feels better to me.

**Comment by Aurimas86** [comment]
I've just stumbled upon folder structure, that looks really good, at http://jasonwatmore.com/post/2016/08/16/angular-2-jwt-authentication-example-tutorial . All file types (services, guards, reducers etc.) except views got their own folders as in ngrx sample. In addition, these folders prefixed with "_" to maintain good folder order. Each feature (pages, components, html etc.) contains its own folder (not in single folder as it's in ngrx example).

**Comment by rob3c** [comment]
@Aurimas86 said:
> Actually, right now, I'm getting the point of Google style guide. Each feature is a module, so when you request a page, it gets lazy loaded, small footprint. Everything is registered at module level. When doing ngrx example way or my suggested way, user will need to wait whole app to download.

I see lazy loading as a key point of feature modules. Most of the actions/effects/reducers/etc are only relevant once a feature module is being used, so ideally there's no need to wait for them to be loaded up front if that part of the app is never accessed.

However, features aren't completely isolated from each other, so at least some module bits need to be available at the global level, if only to provide the actions related to loading the module dynamically. That suggests an eager/lazy split - either within the module itself, or splitting more 'global' code out somewhere else in the project hierarchy (possibly adding tighter coupling between the module and where it's used.)

**Comment by Codermar** [comment]
@dancancro I like the idea of shortening names, it's really hard to read those long and repetitive names. IDEs for the most part will show part of the file path so it makes it easy to tell them apart (at least in Webstorm it is if you have the file tab panel to the right instead of the top. Also, I like the Store files are separate from UI files. Naming container components "page" seems a bit award however, a page may contain potentially several of these.
Use Case:
```
        Entity detail Page
----------------------------------------------
  read only details  (or toggle view/edit)    
----------------------------------------------
------- child routes with associated items ----
tab1 | tab2 | tab3
----------------------------------------------
     Associated Item tab info
----------------------------------------------
```

**Comment by dancancro** [comment]
Hmm, let's think about this.

What if "tab" were another type of component in addition to "page"? So you'd have something like
```
|─ customer
├── page.ts
├── routing.ts
├── orders
│   ├── tab.ts
├── profile
│   ├── tab.ts
├── payments
│   ├── tab.ts
```

or maybe we use "page" for both. Would this present a problem?
```
|─ customer
├── page.ts
├── routing.ts
├── orders
│   ├── page.ts
├── profile
│   ├── page.ts
├── payments
│   ├── page.ts
```

The point would be for the part of the filename preceding the extension (page, detail, list, tab, etc) to, by convention, indicate what kind of component the `@Component` class in that file is.

Then we'd have a glossary somewhere that says something like

`page` - a component that fills the body of the page and can contain details, lists and tabs
`detail` - a component that displays a single entity and must be contained in a page
`list` - a component that displays an iterated list of things and must be contained in a page
`tab` - a detail that fills a tab

We'd need to hash these out but you get the idea.

**Comment by Codermar** [comment]
We're getting there I think. The other aspect of my use case there is that the child routes could have their own workflow of CRUD and therefore is that a "page"? If so, then how can semantically a page be within a page though... If would follow html 5 then that would actually be a "section"?

Take a look at the route definition I have (converted to your example above):
```
const customerViewRoutes: Routes = [
  {
    path: 'view',
    children: [ {
      path: ':id',
      component: CustomerDetailPageComponent,
      children: [{
        path: 'notes',
        loadChildren: 'app/customer/notes/module#NoteModule'
      },
        { path: 'orders', component: CustomerOrderList },
        { path: 'payments', component: CustomerPaymentList },
        { path: 'profile', component: CustomerProfileDetail },
        { path: '', redirectTo: 'notes' } // default
      ]
    }
    ]
  }
];
```
Now "notes" there has its own "page" component which in turn has child routes for listing/editing.
In the case of the tabs, I use a reusable component that contains a <router-outlet></router-outlet> so that makes the content of each tab indiferent to whatever it wants to display.

**Comment by dancancro** [comment]
I think it all depends on how we define each type of component. By a broader definition of 'page' that doesn't limit to things that fill the body of the page, your notes component might be such a thing. But I'd like for page to mean that the thing fills the `<router-outlet>` of the main file `app.page.html`. I hadn't thought of CRUD-workflowness being part of a definition, but it could.

If the notes component displays a list of notes, then maybe 'list' would fit better. If it displays one note at a time then it would seem more like [this](https://github.com/dancancro/great-big-angular2-example/tree/master/src/app/hero/hero-detail) hero detail component or [this](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/crisis/crisis-detail/crisis-detail.component.ts) crisis detail component or [this](https://github.com/dancancro/great-big-angular2-example/blob/master/src/app/contact/contact.page.ts) contact page from Tour of Heroes.

I'm not 100% sure why the Tour of Heroes [files](https://github.com/dancancro/tour-of-heroes-versions) were named as they were. Some include '-detail' and some don't. I suspect that names were not the main point of the demos and this was not thought about as carefully as we're doing here.

I don't think it's critical to form an exhaustive and final taxonomy at this point. We can figure it out as we see more use cases and in the meantime name things that don't fit into any classification 'component.ts' until that happens. But I bet folks on this project have enough experience to get us pretty close if this were the approach the project wanted to take.

**Comment by dancancro** [comment]
Hi all. I came across [this ngrx starter example](https://github.com/NathanWalker/angular-seed-advanced/tree/master/src/client/app) which takes a different file structure approach. Have you seen it? I'm wondering what you think of it.

One big difference from the style guide structure and this example's structure is the use of a `frameworks` directory next to a `components` directory. It puts some "feature" directories (about and home) in `src/client/app/components/` but it also has a sample app located in  `src/client/app/frameworks/sample`

```
.
├── app
│   ├── components
│   │   ├── about
│   │   │   ├── about.component.css
│   │   │   ├── about.component.html
│   │   │   ├── about.component.spec.ts
│   │   │   ├── about.component.tns.css
│   │   │   ├── about.component.tns.html
│   │   │   ├── about.component.ts
│   │   │   └── about.routes.ts
│   │   ├── app.component.html
│   │   ├── app.component.spec.ts
│   │   ├── app.component.tns.html
│   │   ├── app.component.ts
│   │   ├── app.routes.ts
│   │   ├── home
│   │   │   ├── home.component.css
│   │   │   ├── home.component.html
│   │   │   ├── home.component.spec.ts
│   │   │   ├── home.component.tns.css
│   │   │   ├── home.component.tns.html
│   │   │   ├── home.component.ts
│   │   │   └── home.routes.ts
│   │   ├── index.ts
│   │   └── operators.ts
│   └── frameworks
│       ├── analytics
│       │   ├── analytics.module.ts
│       │   ├── index.ts
│       │   └── services
│       │       ├── analytics.service.spec.ts
│       │       └── analytics.service.ts
│       ├── core
│       │   ├── core.module.ts
│       │   ├── decorators
│       │   │   ├── base.component.ts
│       │   │   └── utils.ts
│       │   ├── directives
│       │   │   ├── index.ts
│       │   │   ├── platform.directive.spec.ts
│       │   │   └── platform.directive.ts
│       │   ├── index.ts
│       │   ├── interfaces
│       │   │   ├── iconsole.ts
│       │   │   ├── ilang.ts
│       │   │   ├── index.ts
│       │   │   └── iwindow.ts
│       │   ├── services
│       │   │   ├── console.service.ts
│       │   │   ├── index.ts
│       │   │   ├── log.service.spec.ts
│       │   │   ├── log.service.ts
│       │   │   ├── router-extensions.service.ts
│       │   │   └── window.service.ts
│       │   ├── testing
│       │   │   ├── index.ts
│       │   │   ├── mocks
│       │   │   │   ├── mock-location-strategy.ts
│       │   │   │   ├── ng2-config.mock.ts
│       │   │   │   ├── router-extensions.mock.ts
│       │   │   │   └── window.mock.ts
│       │   │   └── providers
│       │   │       ├── core.ts
│       │   │       ├── http.ts
│       │   │       └── router.ts
│       │   └── utils
│       │       ├── config.spec.ts
│       │       ├── config.ts
│       │       ├── index.ts
│       │       ├── type.ts
│       │       ├── view-broker.spec.ts
│       │       └── view-broker.ts
│       ├── electron
│       │   ├── index.ts
│       │   ├── services
│       │   │   └── event.service.ts
│       │   └── utils
│       │       ├── desktop-config.spec.ts
│       │       └── desktop-config.ts
│       ├── i18n
│       │   ├── actions
│       │   │   ├── index.ts
│       │   │   └── multilingual.action.ts
│       │   ├── common
│       │   │   ├── category.common.ts
│       │   │   └── index.ts
│       │   ├── components
│       │   │   ├── index.ts
│       │   │   ├── lang-switcher.component.css
│       │   │   ├── lang-switcher.component.html
│       │   │   ├── lang-switcher.component.spec.ts
│       │   │   ├── lang-switcher.component.tns.css
│       │   │   ├── lang-switcher.component.tns.html
│       │   │   ├── lang-switcher.component.tns.ios.css
│       │   │   └── lang-switcher.component.ts
│       │   ├── effects
│       │   │   ├── index.ts
│       │   │   └── multilingual.effect.ts
│       │   ├── index.ts
│       │   ├── multilingual.module.ts
│       │   ├── reducers
│       │   │   ├── index.ts
│       │   │   └── multilingual.reducer.ts
│       │   ├── services
│       │   │   ├── i18n.providers.ts
│       │   │   ├── index.ts
│       │   │   ├── multilingual.service.spec.ts
│       │   │   └── multilingual.service.ts
│       │   ├── states
│       │   │   ├── index.ts
│       │   │   └── multilingual.state.ts
│       │   └── testing
│       │       ├── index.ts
│       │       └── mocks
│       │           ├── ng2-config-multilang.mock.ts
│       │           ├── ng2-translate-loader.mock.ts
│       │           └── ng2-translate.mock.ts
│       ├── ngrx
│       │   ├── index.ts
│       │   └── state
│       │       └── app.state.ts
│       ├── sample
│       │   ├── actions
│       │   │   ├── index.ts
│       │   │   └── name-list.action.ts
│       │   ├── common
│       │   │   ├── category.common.ts
│       │   │   └── index.ts
│       │   ├── components
│       │   │   ├── index.ts
│       │   │   ├── navbar.component.css
│       │   │   ├── navbar.component.html
│       │   │   ├── navbar.component.tns.css
│       │   │   ├── navbar.component.tns.html
│       │   │   ├── navbar.component.ts
│       │   │   ├── toolbar.component.css
│       │   │   ├── toolbar.component.html
│       │   │   ├── toolbar.component.tns.css
│       │   │   ├── toolbar.component.tns.html
│       │   │   └── toolbar.component.ts
│       │   ├── effects
│       │   │   ├── index.ts
│       │   │   └── name-list.effect.ts
│       │   ├── index.ts
│       │   ├── reducers
│       │   │   ├── index.ts
│       │   │   └── name-list.reducer.ts
│       │   ├── sample.module.ts
│       │   ├── services
│       │   │   ├── index.ts
│       │   │   ├── name-list.service.spec.ts
│       │   │   └── name-list.service.ts
│       │   └── states
│       │       ├── index.ts
│       │       └── name-list.state.ts
│       └── test
│           ├── e2e
│           │   └── dropdowns.ts
│           ├── index.ts
│           └── shorthand
│               └── ng2-jasmine.ts
├── assets
│   ├── app.config.json
│   ├── data.json
│   ├── favicon
│   │   ├── favicon-DEV.ico
│   │   └── favicon-PROD.ico
│   ├── i18n
│   │   ├── bg.json
│   │   ├── en.json
│   │   ├── es.json
│   │   ├── fr.json
│   │   └── ru.json
│   ├── logo.icns
│   ├── logo.ico
│   └── svg
│       ├── more.svg
│       └── smile.svg
├── css
│   └── main.css
├── index.html
├── main.desktop.ts
├── main.web.prod.ts
├── main.web.ts
├── package.json
├── system-config.ts
├── tsconfig.json
└── web.module.ts
```

@NathanWalker, could you discuss the thinking behind your design? What were your influences? Had you studied the [Angular style guide](https://angular.io/docs/ts/latest/guide/style-guide.html) and this example before taking the direction that you took?

**Comment by Codermar** [comment]
The above sounds good but I still resist the .component. in the name... Why is this necessary?

**Comment by marklagendijk** [comment]
One of the most important properties of any folder structure or architecture is consistency. Many choices don't matter that much, as long as you keep things consistent. In that way the things a developer expects will match what he will find (predictability).
What I see happening a lot, and don't like, is that many open source projects are not following the official styleguide, but without having any solid arguments for it. I would argue that when it comes to subjective points like 'should I include 'component' in the file name, one should always follow the official styleguide. The 'but I like x slightly better' argument doesn't weigh up against the 'decreased predictability' argument, especially for any open source project.

Another very important property of any architecture is re-usability and modularity. How easy is it to take a feature of an app and re-use it in another app. 
The most extreme form of re-usability is a feature which is written as a npm package. When you write (certain) features like that, you can just install them into any app, and use them.
This property is something that is covered well in the official styleguide, as opposed to structures where things are grouped by type (e.g services, directives, reducers etc.).

In the end the choice is up to you. 
For authors open source projects I would recommend to use the official styleguide, and only divert from it if they have a very good reason to do so.
For the architects of commercial projects I would recommend to define important properties which they want their architecture to have. When having done this they preferably should see  if the official styleguide covers these properties, and if so, follow it. If not, they should create their own styleguide.

**Comment by goelinsights** [comment]
Is this discussion making any progress?  I agree that the current split is now an example that fights the feature oriented lazy-loading path highlighted by the core team.  If that's best practice, then highlighting how to do effects and reducers in a lazy-loadeing compatible way would seem to be the best practice path

**Comment by GiantToast** [comment]
I've been organizing things something like this (edited from full structure for clarity):
.
├── app
│   ├── pages
│   │   ├── home
│   │   │   ├── home.component.css
│   │   │   ├── home.component.html
│   │   │   ├── home.component.ts
│   │   │   ├── home.actions.ts
│   │   │   ├── home.routes.ts
│   │   │   ├── home.module.ts
│   │   │   └── home.spec.ts
│   │   ├── pages.module.ts
│   ├── state
│   │   ├── index.ts
│   │   ├── reducers
│   │   │   ├── index.ts
│   │   │   ├── sample.reducer.ts
│   │   ├── effects
│   │   │   ├── index.ts
│   │   │   ├── sample.effects.ts
│   ├── app.component.html
│   ├── app.component.css
│   ├── app.component.ts
│   ├── app.module.ts

My goal was to separate the emitting of actions from the processing of actions.  My reasoning is I want to be able to take out any component, module, service, etc and put it in a library so the rest of the team can use it. I felt that the actions a component can emit should be kept along side the component, but what to do when those actions occur should be up to the individual application.  The has been working pretty well, it's nice having all the state related logic in one area of the application.

**Comment by ryanlangton** [comment]
I keep coming back to this example app and every time I do, I can't help but notice how sloppy the file/folder structure is.  It is not scalable for even the smallest app.  The example app has reducers, state, and selectors all bundled up in a single index.ts file, it's already a mess.  I wish somebody would clean this up as people look to this app for guidance.  We have our folders broken down like this - root level has many feature module folders.  Every feature module folder has the following folders:

- Actions
- Components
- Effects
- Models
- Reducers
- Services
- State

It used to be just a single file instead of a folder, but we discovered that each feature module would often need multiple reducers + state, so this is what it morphed in to.

**Comment by dancancro** [comment]
@ryanlangton What's the difference between your State and Models directories?

What do you think of the argument that two features (pages of the app) might make use of the same slice of the store, just as they may the same tables in relational database, and by Redux doctrine each slice ought to have all reduction/schema centralized in a single reducer/model, therefore the reducer for that slice shouldn't be located in the directory of either feature, but rather in a separate place? I suppose for most slices that is a theoretical unreality, but for things like user or route, it's pretty likely. In other words why not put your Reducers and State/Models directories in a place other than the feature directories?

I agree that there's gotta be a more scalable way to deal with selectors.

Tangentially, granted new Angular best practices are still taking shape, do you find a [resistance](https://gitter.im/angular/angular?at=596d4193f5b3458e3057ea73) in Angular upper thought leadership specifically or web development education generally to preach what you practice or do the obvious departures just make it seem that way?

**Comment by brandonroberts** [comment]
@ryanlangton if you look at the [example-app](https://github.com/ngrx/platform/tree/master/example-app) for V4, its pretty much exactly what you've mentioned. As stated previously, the example-app isn't imposing a structure on you for your application. Its best practices for using ngrx. If patterns emerges from usage, that's fine.

**Comment by mj-interactive** [comment]
Any benefit to move ngrx actions, reducers, etc into a service for component to consume? For example, here is the login-form.component.ts (https://github.com/ngrx/platform/blob/master/example-app/app/auth/components/login-form.component.ts)

Having ngrx imports and implementation wrapped in a feature service might make it easier for components to consume?

**Comment by tommyc38** [comment]
Checkout Nrwl Nx.  It uses its own schematics to create custom cli commands that wire up ngrx scaffolding up for you.  If you are looking for a great way to structure your Angular apps, I highly recommend you give it a shot.  Checkout the video in the link...

https://nrwl.io/nx

**Comment by cedvdb** [comment]
@dancancro I structured my app like the comment above yours.
You said `What do you think of the argument that two features (pages of the app) might make use of the same slice of the store`. 

And I'm hitting exactly this issue. I can't use forFeature, and I combine everything at the root.
