### ISSUE TITLE
'npm run build' throws error

### ISSUE THREAD

**Issue by metanav** [ngrx/example-app#53]
Error: Template parse errors:
Only void and foreign elements can be self closed "path" ("lass=md-checkbox-checkmark xmlns=http://www.w3.org/2000/svg viewBox="0 0 24 24" xml:space=preserve> [ERROR ->]<path class=md-checkbox-checkmark-path fill=none stroke=white d="M4.1,12.7 9,17.6 20.3,6.3"/> </svg> "): MdCheckbox@0:673

**Comment by br1anchen** [comment]
I believe it is caused by [https://github.com/angular/angular.io/issues/2099](url),

you can comment out the `NgcWebpackPlugin` configuration under `production` property of `plugin` in `wepack.config.js`

**Comment by metanav** [comment]
But I guess we will loose AOT then?

**Comment by MikeRyan52** [comment]
It's a bug with @angular/material; it can't be correctly compiled by the AOT compiler yet.

**Comment by metanav** [comment]
Are the material2 team already working on that or we should inform them?

**Comment by br1anchen** [comment]
Hi,

I think it is caused by`NgcWebpackPlugin`, I used `ngc` to do AOT compiling directly, angular2 material sources passed the compiling.

I created a PR regarding to this, it should work.

[https://github.com/ngrx/example-app/pull/57](url)

**Comment by MikeRyan52** [comment]
The build pipeline has been switched to use angular-cli
