### ISSUE TITLE
Does redux feel overwhelming? Or it's just me?

### ISSUE THREAD

**Issue by Aurimas86** [ngrx/example-app#54]
I've learnt this framework, got comfortable working with ngrx. But each time I need to create a new page - I feel overwhelmed by the amount of boilerplate code just to setup it. Lets start with a simple comparison:

Doing it without redux, I need **Service** and **Component** only. It could be expressed as Service->Component->Template. Same as in .NET MVC pattern: Model->Controller->View. _The difference is that .NET MVC is stateless server side app._

However when doing redux, in addition to **Service** and **Component**, you have to do: **Actions**, **Effects**, **Reducers**, **Smart/Dumb Components**, update global AppState, register all these in barrels, inject Actions & Stores a lot. I would say, I need to do **x4 more work** to achieve same result. In most cases all these classes look very similar among different features: load data by id, update loaded model.

Application itself feels like a lot of unrelating pages, that don't share any state, just passing ids around to navigate to another page. Can you give some examples what is good app to use redux and what type of apps should not be using it?

I have found this statement in reactjs/redux documentation. **You’ll know when you need Flux. If you aren’t sure if you need it, you don’t need it.** Does it give answer to my question?

**Comment by bialad** [comment]
I think it depends on the complexity of solution you're trying to solve.

When I started our designing my SAAS-platform, I came from a .Net MVC background. I went with the stateless "MVC for the client"-architecture using AngularJS 1.x with an event-driven service-communication. Which worked really well at first. It's all very simple and I was really productive.

But in time, with customer demands of more features and better performance on both client and server, I starting moving more logic and caching to the client which made the client more and more stateful.  Managing the client state became increasingly difficult, and I was basically on my way to building a homemade redux store. I'm now using the ngrx/store as a replacement of what I was building on my own. :)

My solution and recommendation is to keep using your services (business layer), and have them basically work as wrappers for your store (data layer). At least for me that means I can abstract away the boilerplate to a few services that components (view layer) imports.

**Comment by br1anchen** [comment]
I agree with @bialad 

> I think it depends on the complexity of solution you're trying to solve.

If most of your `states` is just internal (component scoped) ui view usage states, then it is not necessary to use redux/@ngrx-store. But when your component states will have effect on other component states, and there are external events (from server) need to be handled by some components. It is very easy to misuse Angular JS 1.x mechanism either through services or scope boardcast/listener. Then you have to program one event handler with other event handler in services/components...

By using redux methodology, we have to create Actions, Effects and Reducers. We separate each event handler by themselves and only think about each action(event) lead to which effect and what is the next state(only related to this action) should be. We scope the context limited in this way. There is a global app state, but we do not need to think about the whole state all the time, we just need to think about part of the state how it should be changed by action(event), that's it.

I understand it is overwhelming, and many boilerplate code to use redux/@ngrx-store, but it helps me to think/code in a better way.

That is just my opinion.
