### ISSUE TITLE
Is 1.2 Megabytes of minified(!) code a lot for a basic to-do app? 

### ISSUE THREAD

**Issue by ITsvetkoFF** [ngrx/example-app#63]
Just telling my story.
Installed this
`ng serve --prod` worked. 
Saw that bundle file is 1.2Mb.
Tried to inspect.
Saw that there is [some analyzer](https://github.com/robertknight/webpack-bundle-size-analyzer).
Tried to understand how to pass --json flag to webpack that is somewhere inside angular-cli.
Failed

So, let me start the discussion: 

> Is 1.2 Megabytes of minified(!) code a lot for a basic to-do app?

**Comment by Flashwit** [comment]
Probably, but I don't think many people would recommend using a whole suite of Angular2/ngrx etc. for something as simple as this sample app.

**Comment by MikeRyan52** [comment]
As @Flashwit mentioned, the point of this example-app is not to demonstrate a perfectly minified production app. With proper optimizations in the build step, the example app could be made to be much smaller.
