### ISSUE TITLE
Is ngrx/router-store actually used?

### ISSUE THREAD

**Issue by Flashwit** [ngrx/example-app#64]
I noticed that it was added a little while ago but it doesn't appear to actually be used for much. From my understanding, it looks like it's handling router changes so that the State stays up to date with where you are but it doesn't actually use that State for anything.
It allows you to dispatch actions related to changing navigation state but all the links in the example-app are still using [routerLink] to navigate.

Is it in the roadmap to switch to using router-store action dispatches for navigation?

I also allow for the possibility that I'm completely misunderstanding the purpose of router-store.

**Comment by brandonroberts** [comment]
Using router-store allows you to time travel back with the URL associated with the current state. So just like your application will be in a certain state, the URL would have been also.

**Comment by orizens** [comment]
https://github.com/ngrx/router has been deprecated.

**Comment by brandonroberts** [comment]
@orizens @ngrx/router-store works with the @angular/router now

**Comment by orizens** [comment]
@brandonroberts still - the project has been deprecated - no further updates.

**Comment by Flashwit** [comment]
OK yeah, but ngrx/router is irrelevant to this question. ngrx/router-store is still active and it's now compatible with @angular/router.

**Comment by tomwanzek** [comment]
@brandonroberts other than thanks for all the hard work in the ngrx universe :+1:, one quick question:

Does `router-store` capture navigation from [routerLink] as actions? The Readme covers the programmatic navigation, I did not see links mentioned, however.

**Comment by brandonroberts** [comment]
@tomwanzek `router-store` syncs any navigation that happens with the store, whether it be programmatic or declarative.

**Comment by orizens** [comment]
@brandonroberts I just noticed you referred to "ngrx/router-store" and not "ngrx/router" - my mistake.

**Comment by tomwanzek** [comment]
@brandonroberts thanks for the clarification!

**Comment by vijosoco** [comment]
Can I use ngrx/router-store to pass state information along with the navigation of the route?  I have successfully added the  router-store to my project and am using dispatch go and dispatch back to navigate between 2 routes.  I can also see (via the dev tools) that params and query params are being passed around.  I am passing a complex object as a query param, and i can see it in the devtools, but when i subscribe to query params all I see is [Object object].  So it is not clear how I can get at that information.  I am interested in passing state information around as I navigate but am very new to ngrx/router-store and the best way to use it.  Any guidance?
