### ISSUE TITLE
Update to ngrx/store-devtools 3.3.0

### ISSUE THREAD

**Issue by woutervandergraaf** [ngrx/example-app#67]
Update to ngrx/store-devtools 3.3.0 when it's available, to fix time traveling in the redux devtools extension. See [zalmoxisus/redux-devtools-extension#238](https://github.com/zalmoxisus/redux-devtools-extension/issues/238#issuecomment-256230820).

**Comment by zalmoxisus** [comment]
The regression was fixed in `2.8.5` of the extension.

**Comment by brandonroberts** [comment]
Fixed via https://github.com/ngrx/example-app/issues/104
