### ISSUE TITLE
Exception happens after refresh book details

### ISSUE THREAD

**Issue by wizardnet972** [ngrx/example-app#70]
I got exception when I open [book detail url](http://ngrx.github.io/example-app/#/book/g-6na68hPDEC) at the startup, **and I got this book save in my collection**.

`main.05513be….bundle.js:1240 EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'id' of undefined
`

**Comment by Uriziel** [comment]
Can be fixed (?) by adding filter to `getSelectedBook`  selector

```
export function getSelectedBook(state$: Observable<State>) {
  return combineLatest<{ [id: string]: Book }, string>(
    state$.let(getBookEntities),
    state$.let(getSelectedBookId)
  )
  .map(([ entities, selectedBookId ]) => entities[selectedBookId])
  .filter(i => !!i);
}
```

**Comment by MatteoNY** [comment]
Thanks, that also solved the issue when I removed "useHash:" from the RouterModule.

**Comment by brandonroberts** [comment]
This issue is no longer present in the current example
