### ISSUE TITLE
Using DevTools in development but not production

### ISSUE THREAD

**Issue by fiznool** [ngrx/example-app#74]
I realise the point of this app isn't to provide best practices on how to build your app for production.

But, that being said, there are parts of the app (such as the devtools module) that you wouldn't really need/want to be present in production.

Taking the devtools as an example, how would you include this for development but not production?

**Comment by antonyRoberts** [comment]
There are a few steps you can go through depending on your setup or you can use the Chrome and Firefox extension.
[Completely disable monitor in Angular AOT build #20](https://github.com/ngrx/store-log-monitor/issues/20#issuecomment-255273167)

**Comment by brandonroberts** [comment]
See here for an explanation on whether or not to include the extension in production
