### ISSUE TITLE
not working with `ng serve --aot`

### ISSUE THREAD

**Issue by kianmeng-aft** [ngrx/example-app#76]
What I did was 
1) clone https://github.com/ngrx/example-app
2) did a `npm install`
3) did a `ng serve`
4) navigate to `http://localhost:4200/#/book/find` and did a quick search

Everything is working from step 1 - 4. :+1:

Then i proceed to stop the service and did a `ng serve --aot`
everything builds successfully but when i navigate to `http://localhost:4200/#/book/find` to do another  search , it just keep spininng.

What i found out is that its not hitting the effects when run on AOT mode.

So am i actually doing it correctly if i were to try the AOT mode?

Thanks!

```
C:\temp\example-app>ng --version
angular-cli: 1.0.0-beta.17
node: 6.9.1
os: win32 x64

C:\temp\example-app>node --version
v6.9.1

```

**Comment by brandonroberts** [comment]
This is a known issue with the CLI. See https://github.com/angular/angular-cli/issues/2799
