### ISSUE TITLE
Unit Tests?

### ISSUE THREAD

**Issue by JimTheMan** [ngrx/example-app#83]
Hi all, I know some people were complaining in the ngrx hitter chatroom about the lack of tests here. I just finished adding some unit tests to my own ngrx project so I'm willing to help out here and write some for this project. :)

Let me know what I should use though- Jasmine vs mocha, what version, etc.

thanks! :)

**Comment by glitchbane** [comment]
Jasmine has better support for Angular 2, and I would think the latest version?  I too would love to see unit tests here.

**Comment by krjordan** [comment]
@JimTheMan, Jasmine is already included in the project. Feel free to submit a PR with more unit tests!  Duplicate of #45
