### ISSUE TITLE
FullScreen Video Doesn't Fill Entire Screen

### ISSUE THREAD

**Issue by JimTheMan** [ngrx/example-app#84]
Screenshot of video in fullscreen mode:

![screenshot_12_9_16__1_27_pm](https://cloud.githubusercontent.com/assets/5354163/21059958/1a000dce-be13-11e6-92ae-27d8bff756d3.png)

**Comment by krjordan** [comment]
@JimTheMan, Looks like you posted this in the wrong repo.

**Comment by JimTheMan** [comment]
@krjordan oh wow. whoops! Lol

Sorry about that. :)
