### ISSUE TITLE
[Request] Hot module reload support request/ root level reducer

### ISSUE THREAD

**Issue by karolmie1** [ngrx/example-app#90]
Hey! I really like the way you've structured your sample application.
However I have a problem implementing setting root state for hmr with this division of reducers, and no reducer on root level.

Could you please provide an example of root level reducer?

For now i think i will just implement SET_ROOT_STATE in all subreducers.

Repository is great by the way, thanks for showcasing me the power of store!

**Comment by brandonroberts** [comment]
This starter provides an example of using the root state example you are looking for https://github.com/qdouble/angular-webpack2-starter
