### ISSUE TITLE
Action string literals break in TypeScript 2.1+ due to type widening (includes fix)

### ISSUE THREAD

**Issue by rob3c** [ngrx/example-app#93]
Starting with breaking changes in TypeScript 2.1+, string literal types are always widened to strings unless assigned to immutable `const` variables or `readonly` properties. This means things like `switch (action.type)` statements leveraging discriminated unions stop working with the current example-app patterns.

In a [comment in TypeScript issue 2214](https://github.com/Microsoft/TypeScript/issues/2214#issuecomment-268855988), I posted [this link to a TypeScript 2.1 playground](http://www.typescriptlang.org/play/#src=const%20actionTypeCache%3A%20%7B%20%5Btype%3A%20string%5D%3A%20boolean%20%7D%20%3D%20%7B%7D%3B%0D%0A%0D%0Afunction%20ensureSingletonType%3CT%20extends%20string%3E(actionType%3A%20T)%3A%20T%20%7B%0D%0A%20%20%20%20if%20(actionTypeCache%5B%3Cstring%3EactionType%5D)%20%7B%0D%0A%20%20%20%20%20%20%20%20throw%20new%20Error(%60Action%20type%20%22%24%7BactionType%7D%22%20is%20not%20unique%22%60)%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20actionTypeCache%5B%3Cstring%3EactionType%5D%20%3D%20true%3B%0D%0A%20%20%20%20return%20actionType%3B%0D%0A%7D%0D%0A%0D%0A%2F**%20placeholders%20*%2F%0D%0Ainterface%20Action%20%7B%20type%3A%20string%3B%20payload%3F%3A%20any%3B%20%7D%0D%0Ainterface%20Book%20%7B%20id%3A%20string%3B%20%7D%0D%0Ainterface%20State%20%7B%20%7D%0D%0Afunction%20reduceSearch(state%3A%20State%2C%20id%3A%20string)%3A%20State%20%7B%20return%20state%3B%20%7D%0D%0Afunction%20reduceLoad(state%3A%20State%2C%20book%3A%20Book)%3A%20State%20%7B%20return%20state%3B%20%7D%0D%0A%0D%0A%2F********************%20BEGIN%20BROKEN%20********************%2F%0D%0A%0D%0A%2F%2F%20In%20TS%202.1%2B%20these%20properties%20are%20only%20strings%20instead%20of%20literals%2C%0D%0A%2F%2F%20even%20though%20%60ensureSingletonType%60%20returns%20them%20as%20literals.%0D%0Aconst%20ActionTypesBROKEN%20%3D%20%7B%0D%0A%20%20%20%20SEARCH%3A%20ensureSingletonType(%27%5BBook%5D%20Search%27)%2C%0D%0A%20%20%20%20LOAD%3A%20ensureSingletonType(%27%5BBook%5D%20Load%27)%0D%0A%7D%3B%0D%0A%0D%0Aclass%20SearchActionBROKEN%20implements%20Action%20%7B%0D%0A%20%20%20%20%2F%2F%20In%20TS%202.1%2B%20this%20is%20only%20a%20string%20instead%20of%20a%20string%20literal%0D%0A%20%20%20%20type%20%3D%20ActionTypesBROKEN.SEARCH%3B%20%0D%0A%20%20%20%20constructor(public%20payload%3A%20string)%20%7B%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20LoadActionBROKEN%20implements%20Action%20%7B%0D%0A%20%20%20%20%2F%2F%20In%20TS%202.1%2B%20this%20is%20only%20a%20string%20instead%20of%20a%20string%20literal%0D%0A%20%20%20%20type%20%3D%20ActionTypesBROKEN.LOAD%3B%0D%0A%20%20%20%20constructor(public%20payload%3A%20Book)%20%7B%20%7D%0D%0A%7D%0D%0A%0D%0Atype%20ActionsBROKEN%20%3D%20SearchActionBROKEN%20%7C%20LoadActionBROKEN%3B%0D%0A%0D%0Afunction%20reducerBROKEN(state%20%3D%20%7B%7D%2C%20action%3A%20ActionsBROKEN)%3A%20State%20%7B%0D%0A%20%20%20%20switch%20(action.type)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20ActionTypesBROKEN.SEARCH%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20id%20%3D%20action.payload%3B%20%2F%2F%20still%20string%20%7C%20Book%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20reduceSearch(state%2C%20id)%3B%20%2F%2F%20type%20narrowing%20is%20BROKEN!%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20case%20ActionTypesBROKEN.LOAD%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20book%20%3D%20action.payload%3B%20%2F%2F%20still%20string%20%7C%20Book%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20reduceLoad(state%2C%20book)%3B%20%2F%2F%20type%20narrowing%20is%20BROKEN!%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20default%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20state%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F********************%20END%20BROKEN%20********************%2F%0D%0A%0D%0A%2F********************%20BEGIN%20WORKS%20********************%2F%0D%0A%0D%0A%2F%2F%20In%20TS%202.1%2B%20const%20variables%20and%20readonly%20properties%20are%0D%0A%2F%2F%20required%20to%20preserve%20literals.%20Unfortunately%2C%20we%20can%27t%0D%0A%2F%2F%20declare%20anonymous%20objects%20with%20readonly%20properties%2C%20so%0D%0A%2F%2F%20we%20use%20a%20class%20here%20with%20static%20readonly%20properties%20to%0D%0A%2F%2F%20to%20capture%20the%20actions%20as%20string%20literals%20in%20one%20place.%0D%0Aclass%20ActionTypesWORKS%20%7B%20%0D%0A%20%20%20%20static%20readonly%20SEARCH%20%3D%20ensureSingletonType(%27%5BBook%5D%20Search%27)%3B%0D%0A%20%20%20%20static%20readonly%20LOAD%20%3D%20ensureSingletonType(%27%5BBook%5D%20Load%27)%3B%0D%0A%7D%3B%0D%0A%0D%0Aclass%20SearchActionWORKS%20implements%20Action%20%7B%0D%0A%20%20%20%20%2F%2F%20TS%202.1%2B%20requires%20readonly%20to%20preserve%20literals%0D%0A%20%20%20%20readonly%20type%20%3D%20ActionTypesWORKS.SEARCH%3B%20%0D%0A%20%20%20%20constructor(public%20payload%3A%20string)%20%7B%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20LoadActionWORKS%20implements%20Action%20%7B%0D%0A%20%20%20%20%2F%2F%20TS%202.1%2B%20requires%20readonly%20to%20preserve%20literals%0D%0A%20%20%20%20readonly%20type%20%3D%20ActionTypesWORKS.LOAD%3B%0D%0A%20%20%20%20constructor(public%20payload%3A%20Book)%20%7B%20%7D%0D%0A%7D%0D%0A%0D%0Atype%20ActionsWORKS%20%3D%20SearchActionWORKS%20%7C%20LoadActionWORKS%3B%0D%0A%0D%0Afunction%20reducerWORKS(state%20%3D%20%7B%7D%2C%20action%3A%20ActionsWORKS)%3A%20State%20%7B%0D%0A%20%20%20%20switch%20(action.type)%20%7B%0D%0A%20%20%20%20%20%20%20%20case%20ActionTypesWORKS.SEARCH%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20id%20%3D%20action.payload%3B%20%2F%2F%20string%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20reduceSearch(state%2C%20id)%3B%20%2F%2F%20type%20narrowing%20WORKS!%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20case%20ActionTypesWORKS.LOAD%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20book%20%3D%20action.payload%3B%20%2F%2F%20Book%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20reduceLoad(state%2C%20book)%3B%20%2F%2F%20type%20narrowing%20WORKS!%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20default%3A%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20state%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F********************%20END%20WORKS%20********************%2F%0D%0A) that shows how to update the example app for 2.1+.

Here's the full playground code, for reference:
```typescript
const actionTypeCache: { [type: string]: boolean } = {};

function ensureSingletonType<T extends string>(actionType: T): T {
    if (actionTypeCache[<string>actionType]) {
        throw new Error(`Action type "${actionType}" is not unique"`);
    }
    actionTypeCache[<string>actionType] = true;
    return actionType;
}

/** placeholders */
interface Action { type: string; payload?: any; }
interface Book { id: string; }
interface State { }
function reduceSearch(state: State, id: string): State { return state; }
function reduceLoad(state: State, book: Book): State { return state; }

/******************** BEGIN BROKEN ********************/

// In TS 2.1+ these properties are only strings instead of literals,
// even though `ensureSingletonType` returns them as literals.
const ActionTypesBROKEN = {
    SEARCH: ensureSingletonType('[Book] Search'),
    LOAD: ensureSingletonType('[Book] Load')
};

class SearchActionBROKEN implements Action {
    // In TS 2.1+ this is only a string instead of a string literal
    type = ActionTypesBROKEN.SEARCH; 
    constructor(public payload: string) { }
}

class LoadActionBROKEN implements Action {
    // In TS 2.1+ this is only a string instead of a string literal
    type = ActionTypesBROKEN.LOAD;
    constructor(public payload: Book) { }
}

type ActionsBROKEN = SearchActionBROKEN | LoadActionBROKEN;

function reducerBROKEN(state = {}, action: ActionsBROKEN): State {
    switch (action.type) {
        case ActionTypesBROKEN.SEARCH: {
            const id = action.payload; // still string | Book
            return reduceSearch(state, id); // type narrowing is BROKEN!
        }
        case ActionTypesBROKEN.LOAD: {
            const book = action.payload; // still string | Book
            return reduceLoad(state, book); // type narrowing is BROKEN!
        }
        default:
            return state;
    }
}

/******************** END BROKEN ********************/

/******************** BEGIN WORKS ********************/

// In TS 2.1+ const variables and readonly properties are
// required to preserve literals. Unfortunately, we can't
// declare anonymous objects with readonly properties, so
// we use a class here with static readonly properties to
// to capture the actions as string literals in one place.
class ActionTypesWORKS { 
    static readonly SEARCH = ensureSingletonType('[Book] Search');
    static readonly LOAD = ensureSingletonType('[Book] Load');
};

class SearchActionWORKS implements Action {
    // TS 2.1+ requires readonly to preserve literals
    readonly type = ActionTypesWORKS.SEARCH; 
    constructor(public payload: string) { }
}

class LoadActionWORKS implements Action {
    // TS 2.1+ requires readonly to preserve literals
    readonly type = ActionTypesWORKS.LOAD;
    constructor(public payload: Book) { }
}

type ActionsWORKS = SearchActionWORKS | LoadActionWORKS;

function reducerWORKS(state = {}, action: ActionsWORKS): State {
    switch (action.type) {
        case ActionTypesWORKS.SEARCH: {
            const id = action.payload; // string
            return reduceSearch(state, id); // type narrowing WORKS!
        }
        case ActionTypesWORKS.LOAD: {
            const book = action.payload; // Book
            return reduceLoad(state, book); // type narrowing WORKS!
        }
        default:
            return state;
    }
}

/******************** END WORKS ********************/
```

**Comment by jinder** [comment]
Great work @rob3c!  I've found that in 2.1.5 at least, you don't need to turn ActionTypesWORKS into a class, provided the .type property of the action is readonly.  I'm not sure if this is a bug in TypeScript though, as you could conceivably change the value inside the const.

**Comment by jinder** [comment]
No, it's not showing as string literal in 2.1.5 (at least according to my VSCode intellisense).  But if you discriminate based on it in the switch statement, it narrows the type accordingly.

**Comment by dereklin** [comment]
It seems this problem has gone away in typescript 2.1.6

**Comment by brandonroberts** [comment]
This will be addressed once Angular version 4 is released. See https://github.com/ngrx/example-app/pull/88#issuecomment-272623083
