### ISSUE TITLE
`type` method should be in main lib

### ISSUE THREAD

**Issue by cyrilrbt** [ngrx/example-app#98]
My reasoning is that this method seems to be pretty important in the official example app. It should be bundled in the library.

**Comment by vespertilian** [comment]
I agree. Would be nice if it was at least provided as a package. 

Importing it would be nicer from NPM package as well

This:

`import {type} from "../../../util";`
`import {type} from "../../../../../util";` depending on how deep your component tree goes. 

vs

`import {type} from "@ngrx/type";` <- Nicer

**Comment by vespertilian** [comment]
@MikeRyan52 

Mike, if you are up for this I could work on this next week.

**Comment by brandonroberts** [comment]
The type lib won't be needed once TypeScript 2.1 support is finished. See https://github.com/ngrx/example-app/pull/88#issuecomment-272623083

**Comment by vespertilian** [comment]
@brandonroberts Awesome!
