### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by marklagendijk** [ngrx/example-app#99]
It would be great if we have unit tests with 100% coverage, so people can also learn how to test all the ngrx stuff.

**Comment by vespertilian** [comment]
Here are some sample test's I hope to get merged in, pending a style review. 

https://github.com/vespertilian/example-app/blob/master/src/app/effects/collection.spec.ts
https://github.com/vespertilian/example-app/blob/master/src/app/reducers/book.spec.ts

**Comment by krjordan** [comment]
Duplicate of #45
